// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcvnvmebosgjhylksmiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjdm52bWVib3Nnamh5bGtzbWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NjcyODksImV4cCI6MjA3MTI0MzI4OX0.rwJo3_Lyjl0aIJGJNri_QgFlmHmP4RuLGfGdQzV_hRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});